### PR TITLE
Fix for Issue #26 and #27

### PR DESCRIPTION
**Pull request by 28Ritu**
Fix for Issue #26 and #27 .
@championswimmer Kindly review this.

### CODE REVIEW

**Comment by 28Ritu** [comment]
@ananay Done.

**Comment by championswimmer** [comment]
please prefer solving one issue at a time. one pr for each issue, unless they are so inter-related that they cannot be handled separately

**Comment by 28Ritu** [comment]
Apologies for the inconvenience. Actually forgot to create a separate branch. I'll take care next time. :)

**Comment by 28Ritu** [comment]
@championswimmer  I've created separate PRs for the issues:
**Issue #26:** #65 
**Issue #27:** #66 
Kindly review them.

**Pull request closed without merging**
