### PR TITLE
Setup Gradle Play Publisher With advanced Versioning

### LINKED ISSUE #120: Setup Gradle Play Publisher
**Expected Behaviour**
Should take version code and version name from date and also set the minor major version in advance versioning.

**Steps to reproduce it**
https://github.com/Triple-T/gradle-play-publisher

**Expected Bounty**
1000

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #120 

**Changes:**
Setup for Gradle play Publisher with advance versioning for automating publishing to Play store.
GitHub - Triple-T/gradle-play-publisher: 
https://github.com/Triple-T/gradle-play-publisher

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya do i need to add readme as well?

**Comment by aggarwalpulkit596** [comment]
@the-dagger kindly review this pr also

**Comment by championswimmer** [comment]
@aggarwalpulkit596 preferrably yes

**Comment by aggarwalpulkit596** [comment]
@championswimmer done bhaiya and I've also fixed the mixing of  others pr

**Comment by aggarwalpulkit596** [comment]
@championswimmer this pr can also be merged i guess ?

**Pull request closed without merging**
