### PR TITLE
Fix app crash on launch #96

### PR DESCRIPTION
**Pull request by RishabhRawatAndroid**
## Fix the #96 
Fix the issue which give the `io.realm.exception.RealmPrimaryKeyConstraintException`

screenshot_2018-06-02-22-13-20-755_com miui bugreport

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Already fixed

**Comment by aggarwalpulkit596** [comment]
Already fixed

**Comment by RishabhRawatAndroid** [comment]
@aggarwalpulkit596  **You can merge 2 issue in single PR.**

**Comment by championswimmer** [comment]
please fix the conflicts

**Comment by RishabhRawatAndroid** [comment]
@championswimmer this `realm.copyToRealmOrUpdate(room);` already present in the code (Means this line of code already merge from another contributor PR) that's why there is no change in this PR,
@championswimmer I not get the 200 point and my PR is already merged. Mt issue is #61  and merged PR is #71

**Comment by aggarwalpulkit596** [comment]
it has been already solved and merged

**Pull request closed without merging**
