### PR TITLE
Icons for the app

### PR DESCRIPTION
**Pull request by ArushiSinghal**
@the-dagger 
Issue #3

### CODE REVIEW

**Comment by the-dagger** [comment]
Just add one file named ic_launcher.png in the `mipmap-xxx` folders.
Replace the existing one with the new one that you created.

**Comment by ArushiSinghal** [comment]
@the-dagger done

**Comment by abishekvashok** [comment]
Can you replace the round ones as well?

**Comment by ArushiSinghal** [comment]
@abishekvashok I want to know with what I should replace round ones. I have removed the existing round ones. Should I make these Icons in round shape also?

**Comment by abishekvashok** [comment]
@ArushiSinghal yes if you could.

**Comment by ArushiSinghal** [comment]
@abishekvashok please review.

**Comment by the-dagger** [comment]
@ArushiSinghal Please also add a 512x512px icon in the root folder of the source code.
We might need it when we publish the app on google ply.

**Comment by ArushiSinghal** [comment]
@the-dagger I am not able to get you. Please explain me more briefly.

**Comment by the-dagger** [comment]
@ArushiSinghal What I meant was, also add a 512X512 px icon to the root directory.
https://github.com/coding-blocks/Chatter

We might need this icon while we publish the app to google play store since that requires the developer to publish a 512 X 512 resolution icon.

**Comment by ArushiSinghal** [comment]
@the-dagger Please review.

**Comment by ArushiSinghal** [comment]
@the-dagger please add bounty so that I can place the claim for this.

**Comment by championswimmer** [comment]
This is the Macbook Messages App icon. It has a copyright. Can we not do such a shoddy job please ? 

@ArushiSinghal there's something called copyright laws? Hope you read up on them
@the-dagger  please revert this. and please do minimum necessary background check before merging image assets

**Comment by the-dagger** [comment]
@championswimmer done, sorry about that.
Will keep that in mind.

**Comment by abishekvashok** [comment]
I am sorry for giving an approve without checking for copyright as I thought it was hand made and I swear I haven't used an apple product. Sorry.

**Pull request merged**
