### PR TITLE
Adds message display support

### PR DESCRIPTION
**Pull request by abishekvashok**
Defined the UI for the room, adds onClick listener for each room_item
inside the RoomsFragment which opens a newly created new RoomFragment
which displays the messages down in a recycler view with the help of
MessagesAdapter. Messages will be taken from the Gitter Api and be
updated with the newly created MessagesTable which is a RealmObject.

Soft updation support has been added for messages and rooms which means
that any update made in the message or rooms would instantly reflect to
the user when he becomes online with much less lines of code by making
sorting done with the help of message's id. Based on the concept that
newly added messages will have a greater value than the previous ones.

In addition to the above, network calls will be timed based on user's
network connectivity and the app will request the user to connect to
internet only when there are no messages or rooms and internet access.

OkHTTP has been used as usual to query the Gitter Api passing along the
authorisation code.

Fixes: #7 

CC: @the-dagger @championswimmer

### CODE REVIEW

**Comment by abishekvashok** [comment]
@the-dagger can you take a look

**Comment by the-dagger** [comment]
@abhishekvashok my system is out for repair, should be back by Monday. 
Will take a look then.

**Comment by abishekvashok** [comment]
@the-dagger sure take your own time.

**Comment by abishekvashok** [comment]
Any updates @the-dagger

**Comment by abishekvashok** [comment]
@the-dagger pls add bounties :P

**Comment by abishekvashok** [comment]
@championswimmer @the-dagger bounties?

**Pull request merged**
