### PR TITLE
Materialize The App

### LINKED ISSUE #97: Materialize the app
The UI of the app is lacking in many aspects, this needs some tweaking.

Changes needed :
 
* Removing BottomNavigationBar and having 2 Activities, one for the rooms and other for messages.

* Getting rid of unnecessary activities and fragments

* Having a PreferenceActivity

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #97 

**Changes:**
Added Room Activity and Prefence Activity
Removed Unnecessary Fragments
Removed BottomNavigationbar in DashBoard Activity
**Screenshots for the change:**
screenshot-1527955081162

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
screenshot-1527955097784
screenshot-1527955107438

**Comment by aggarwalpulkit596** [comment]
@championswimmer kindly review this pr as well

**Comment by the-dagger** [comment]
@aggarwalpulkit596 Can we have different fontSize for message, the sender name, date, etc.
Also please make the sender name as bold and make the links clickable.

**Comment by aggarwalpulkit596** [comment]
Okay sure will do that right away

**Comment by aggarwalpulkit596** [comment]
@the-dagger should i add images too in the messages?

**Comment by aggarwalpulkit596** [comment]
@the-dagger bhaiya also check it  is showing conflict when i try to add userimage in the adapter

**Comment by the-dagger** [comment]
@aggarwalpulkit596 No need to use cards for the list item here in the chat rooms.
It makes the content harder to read.

Cards generally should be avoided in a RecyclerView if the content is distinct enough or doesn't contain rich visual content.

**Comment by aggarwalpulkit596** [comment]
Okay @the-dagger  will do that asap and kindly review code for database restructuring.

**Comment by aggarwalpulkit596** [comment]
screenshot-1528205998333
Fixed Layout

**Pull request merged**
