### PR TITLE
Adds support for sending messages

### LINKED ISSUE #10: Add support for sending messages and drafts
The following steps would need to be taken:

- [ ] Implement input `TextBox` along side the `RecyclerView` which currently takes the complete height of the parent.
- [ ] Implement sending the message when internet is available with the help of Gitter API
- [ ] Add a new column called `DraftMessage` in the `RoomsTable` which will give us drafted message support.
- [ ] Modify the `MessagesTable` and add another column called syncState which denotes the whether the message has been synced or not. (This is extremely usefull when internet is not available)
- [ ] Implement SyncAdapter to sync not synced items in `MessagesTable` to be synced with Gitter.
- [ ] Implement broadcast recievers, stub content provider and services to support the SyncAdapter 
- [ ] Make sure the message is sent as sync adapter fails in certain circumstances.

Difficulty: Hard

CC: @championswimmer @the-dagger

Please add bounty points :)

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds message sending support alng with drafts. Adds a EditText inside
the RoomFragment along with a send button for sending the messages.
Messages once typed in will be saved as draft for the room in a new
column in the RoomsTable. Message will be sent if internet is vaialable
or the next time it becomes available using the SyncAdapter.

Messages will be synced using the SyncAdapter to the Gitter database
using a simple logic which will enable the messages to be automatically
synced to the Gitter Database using it's API.

Since, we are not dealing with any types of accounts, stub content
providers and account managers have been setup.

Message will be sent using OkHTTP and the Gitter API.

Closes #10 

CC: @the-dagger @championswimmer

### CODE REVIEW

**Comment by championswimmer** [comment]
@the-dagger please check

**Comment by the-dagger** [comment]
@abishekvashok can you double check to see if the butterknife calls are working fine on you end?
I don't think that they are working properly, every widget initialized using butterknife gives a NPE whereas when done via findVIewById it is working just fine.

Also please switch to stable studio from Canary for building this app.
Thanks!

**Comment by abishekvashok** [comment]
> Also please switch to stable studio from Canary for building this app.

Downloading. We have really slow internet in homes in the south of India.

**Comment by abishekvashok** [comment]
> @abishekvashok can you double check to see if the butterknife calls are working fine on you end?
I don't think that they are working properly, every widget initialized using butterknife gives a NPE whereas when done via findVIewById it is working just fine.

That's wieredthat you are getting null pointers. It's working in my father mi note 4. I remember reading somewhere that instant run runs into trouble when used with butterknife. But, I would try testing it online as well and let you know. Till then can you take a look at #7 pinky please and add a bounty as it was solved.

**Comment by abishekvashok** [comment]
Any updates @the-dagger it's working in my end.

**Comment by abishekvashok** [comment]
@the-dagger pls check now.

**Comment by abishekvashok** [comment]
Squashed it.

**Pull request merged**
