### PR TITLE
fix the message layout and message order and recognize the web link i…

### PR DESCRIPTION
**Pull request by RishabhRawatAndroid**

### CODE REVIEW

**Comment by RishabhRawatAndroid** [comment]
@championswimmer Please review this PR because all check has been passed from the **Travis CI**.
And At last, I mistakenly claim the wrong issue with a wrong pull request. So, Is there any way to delete the claim if mistakenly done in leaderboards in Boss. Please add the 200 bounty point in RishabhRawatAndroid. At last sorry :(

My issue is #61 and PR is #71.

**Comment by manav-mj** [comment]
You have done a lot of changes that are not related to the issue. Please open a separate issue and do the changes accordingly.

Changes not related to the issue are
1. Gitter API change
2. Changes on logic for the realm object `roomId` changed to `uId`.

There is already a PR submitted for the issues regarding the crash of RoomFragment #53

**Comment by aggarwalpulkit596** [comment]
@RishabhRawatAndroid yes there are a lot of issues in a single pr you shouldn't be doind that much changes in a single pr

**Comment by RishabhRawatAndroid** [comment]
@manav-mj  @aggarwalpulkit596  All things are change according to the issue.

**Comment by championswimmer** [comment]
reopen pr if you're still working on it

**Pull request closed without merging**
