### PR TITLE
add app screenshots to readme 

### PR DESCRIPTION
**Pull request by mohancm**
refered from #14

### CODE REVIEW

**Comment by championswimmer** [comment]
why is the travis file part of this commit ?

**Comment by mohancm** [comment]
Oops, by mistake I pushed to same branch
I will reset it :)

**Comment by mohancm** [comment]
@championswimmer i have resetted it :)
its fine now

**Comment by mohancm** [comment]
@championswimmer anything wrong?

**Comment by championswimmer** [comment]
old screenshots, app has now changed a bit

**Pull request closed without merging**
