### PR TITLE
Added circle ci and travis test

### LINKED ISSUE #180: Set up unit test and run them on travis/circleci

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #180

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer done

**Comment by championswimmer** [comment]
i think this 
https://github.com/aggarwalpulkit596/Chatter/blob/70e501541f7359d6695ec33047e390a4e6bf56da/app/src/androidTest/java/com/codingblocks/chatter/WebViewActivityTest.java 
is an integration test, not a unit test. and hence cannot be tested with `gradlew test` only. it needs `connectedCheck`

**Comment by championswimmer** [comment]
unit test should be something that does not require to run on device.

for eg these are unit tests
https://github.com/coding-blocks/DigitalOceanApp/blob/master/doandroidlib/src/test

these are integration tests
https://github.com/coding-blocks/DigitalOceanApp/tree/master/app/src/androidTest/java/in/tosc/digitaloceanapp

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya my claim isn't accepted yet do i need to something else ? i mean i can make pull request as this has already been merged for connectedTest if you say so although i have tested these test and i have coverage report for them as well

**Pull request merged**
