### PR TITLE
Added Message Info And fix for user activity

### LINKED ISSUE #159: Add Message Info
Add Message Info on long click of a particular message item in Rooms Fragment

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #159 

**Changes:**
On long click of message item message info pops up 
Recyclerview works the same as for roominfo
**Screenshots for the change:**
screenshot-1534018125504

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@the-dagger @championswimmer please review

**Comment by aggarwalpulkit596** [comment]
@championswimmer resolved conflicts

**Comment by the-dagger** [comment]
@aggarwalpulkit596 
https://travis-ci.org/coding-blocks/Chatter/builds/415571844#L2197

**Comment by aggarwalpulkit596** [comment]
@the-dagger fixing the error in a moment

**Pull request merged**
