### PR TITLE
Added Group Info Page

### LINKED ISSUE #143: Added a Page for Group info
There should be a page for Group Info with a list of the all the users as well as a list of admins

**Expected Bounty**

2000

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #143 

**Changes:**
Added Group Info Bottom Sheet

**Screenshots for the change:**
videotogif_2018 08 01_09 29 49

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer @the-dagger bhaiya is this design good enough?

**Comment by abishekvashok** [comment]
I can see commits not related to this PR here, can you rebase it properly pls?

**Comment by aggarwalpulkit596** [comment]
Actually they are somehow connected as api update is required by leave room and leave room will be added to group info

**Comment by abishekvashok** [comment]
It's because you sent the project from the same branch. Can you rebase it?

**Comment by aggarwalpulkit596** [comment]
I can squash commits if you want but as i told you i want api update and leave room commits in this branch
and first two commits cannot be resolved as i have made a pull request on base branch and these commmits cannot be merged in the base branch

**Pull request closed without merging**
