### PR TITLE
Navigation drawer

### LINKED ISSUE #135: Add Navigation Drawer
Add Navigation Drawer for displaying user info as currently there is no option to see user profile info

it should not be worked upon before #134 is merged/fix as uid is required for leaving a room

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fixes #135

**Changes:**
Added Navigation Drawer for displaying user info

**Screenshots for the change:**
screenshot-1532791684578

### CODE REVIEW

**Comment by championswimmer** [comment]
A navdrawer only for so little info makes very little sense. Why not just use signout menu action from actionbar ?

**Comment by aggarwalpulkit596** [comment]
We can add a lot more functions in the nav Drawer for example user favourite,unread items,user created room/community or list of one to one chat

**Comment by aggarwalpulkit596** [comment]
And the also there is no option to show user information and i think there and there are lot of user resources which can be used https://developer.gitter.im/docs/user-resource

**Comment by aggarwalpulkit596** [comment]
screenshot-1532979780508
We can do something like this with the nav drawer

**Pull request closed without merging**
